### ISSUE TITLE
Return CompletableFuture instead of Publisher in HttpHandler

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#10]
I create the issue in order to discuss/experiment about the idea of a more explicit API for single element  `Publisher` or `Publisher<Void>` in Framework API (it is not about handler methods return types).

Reactor has support for such need with its [`Promise`](http://projectreactor.io/docs/api/reactor/rx/Promise.html) type, and RxJava has recently introduced the [`Single`](http://reactivex.io/documentation/single.html) type to manage such need, but we should remain not based on a specific Rx implementation at Framework API level.

For example, [`HandlerResultHandler#handleResult()`](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/reactive/web/dispatch/HandlerResultHandler.java#L30
) current API is:
```java
Publisher<Void> handleResult(ServerHttpRequest request, ServerHttpResponse response, HandlerResult result)
```

Reactive Streams provides nothing for that out of the box, but since Spring Reactive is Java 8+, one possible option is to use `CompletableFuture<T>` for such need.
```java
CompletableFuture<Void> handleResult(ServerHttpRequest request, ServerHttpResponse response, HandlerResult result)
```

We could also introduce a new `@Single` annotation to express this semantic (same idea than `javax.annotation.Nonnull` annotation), for example:
```java
@Single
Publisher<Void> handleResult(ServerHttpRequest request, ServerHttpResponse response, HandlerResult result)
```

Please notice that  `CompletableFuture<T>` and `@Single Publisher<T>` have not exactly the same semantics because the first is just an async non-blocking future result while the second contains the additional capability to also explicitly request the data via `Subscription#request(long n)`. This is from my POV what could allow us to make the choice between both solutions.

For the `HandlerResultHandler#handleResult()` specific use case, the purpose of this `Publisher<Void>` is to signal the end of the handler method processing, and since we control when the handler method is invoked, I think returning `CompletableFuture<Void>` may be enough ...

Any thoughts?

**Comment by sdeleuze** [comment]
You can notice that [ReactiveSocket also makes the distinction](https://github.com/ReactiveSocket/reactivesocket/blob/master/Motivations.md#requestresponse-single-response) between `Future` and `Publisher` to explicit different behaviors.

**Comment by sdeleuze** [comment]
I updated this issue to make it more focused on the `HttpHandler#handle()` return type, since from my POV the return value should effectively be a `CompletableFuture<Void>`, since we don't need `Publisher<Void>` additional behavior for that use case where we just wait the completion or an error from the handler implementation.

It also simplify the code since it avoids unnecessary `Publisher` -> Reactor `Stream` wrapping and make `HttpHandler` purpose more simple to understand.

I have submitted pull request https://github.com/spring-projects/spring-reactive/pull/15 with that change implemented.

**Comment by rstoyanchev** [comment]
My main concern with CompletableFuture is the implications on not having a uniform data pipeline vs inserting something like a CompletableFuture which has no awareness of demand signals for example. I believe @smaldini expressed similar concern in a comment but I can't find it now.

Speaking of the Reactor Promise, it is a `reactor.rx.Stream` and hence the same concern doesn't apply there. As for rx.Single there is no common type with rx.Observable, nevertheless like an Observable it is aware of backpressure signals, etc.

**Comment by smaldini** [comment]
I am also concerned by lack of expressing pipelines end to end, however like Single, Promise and Stream are disjoint (just both implementing Publisher).

I am also thinking that if reactor-core keeps moving on that basic facility for RS, maybe a simple "Single" interface marker could at least extend a Publisher and eventually add:
- onSuccess(Consumer) // to become JDK8 Consumer
- onError(Consumer) //to become JDK 8 Consumer

But in the end, I'm also not sure about that Single vs Stream story 100% myself, I know that debate was and is all the rage but IMO the Promise , Single or CompletableFuture types are encouraging a behavior we try to move away from : blocking features (await etc). If handlers become composable and if we have to expand our reach to any Network pipelining, we will need the Stream-like combinatory operation (or at least the Promise ones or Single ones if we still want to mark single result, which are subset of Stream/Observable but not override).

**Comment by sdeleuze** [comment]
I understand this concern, and in fact I changed my mind regarding methods returning a single element like the ones in Spring Data reactive support discussed on issue https://github.com/spring-projects/spring-reactive/issues/12 to use `Publisher` instead of `CompletableFuture`, and have updated this issue description accordingly.

But I am wondering if this applies to the `CompletableFuture<Void>` return value discussed here because:
 - We are talking about a `CompletableFuture<Void>` that does not transmit any data
 - We are controlling when the handler is invoked
 - You can see in the [HttpHandlerServlet](https://github.com/spring-projects/spring-reactive/pull/15/files#diff-5ec43aed7ed181cd85273e890dd1b2f1) changes that we are subscribing and requesting `Long.MAX_VALUE` elements just after calling `HttpHandler#handle()`. So in practice, we don't use subscription and back-pressure on this Publisher<Void>.
 - `*Async` methods of `CompletableFuture` allow to specify an `Executor` -> equivalent to `subsribeOn()`

In `Publisher<Void> writeWith(Publisher<ByteBuffer> contentPublisher)`, from my POV the stream where we need to handle subscription, back-pressure, etc. is the `Publisher<ByteBuffer>` that represent the response body. `Publisher<Void>` seems to be only here to signal the end of the processing of the request/response. That why I think `CompletableFuture<Void> writeWith(Publisher<ByteBuffer> contentPublisher)` seems to be less confusing. It clearly express the fact that we don't support any kind of backpressure and deferred subscription here, its only purpose is the signal the end of the processing.

**Comment by smaldini** [comment]
Yep I understand the concern with Void and not requesting.
Thing is Complete signals from Publisher or alike are well understood by operations such as concat, flatmap, zip. Error signals are also well managed with a series of dedicated operation. SubscribeOn has still some value too if implemented accordingly: asynchronously scheduling the .subscribe call itself in addition to the .request call, still making the original Publishers.create / Observable.create a non opinionated pipeline wrt threading.

**Comment by sdeleuze** [comment]
Not directly related to the `CompletableFuture` vs `Publisher` question, but see also [this interesting discussion](https://github.com/ReactiveX/RxJava/issues/3037) on RxJava issue tracker about the `reponse.write()` return value semantic.

**Comment by smaldini** [comment]
Note that related to that discussion, Reactor solves it by having a Stream#after() method:

```java
channel.writeWith(stream)
.concatWith(
    Streams.timer(3).after()
)
.concatWith(channel.writeWith(endResponse));
```

**Comment by sdeleuze** [comment]
@smaldini My point is not about saying `subscribeOn` has no advantage, just that in the specific case this issue is about (ie. what should be the return type of `HttpHandler#handle()` and `ServerHttpResponse#writeWith()`), this capabilities are not used (cf. current implementation).

Someone could argue that we may perhaps need that later. I don't see any use case when it would be needed. If we can't find such concrete use case, my proposal is to switch to `CompletableFuture<Void>` that provide only the semantics we use and want to express through our API.

If we encounter later a use case where `Publisher<Void>` is needed, we will understand exactly why we need it and will have the opportunity to roll-back to `Publisher<Void>`, after all spring-reactive is just a sandbox where we try to find the footprint of what we need.

I think I would prefer this "do less, and change if we see concretely why we need it" rather that continue to use `Publisher<Void>` for months, and don't really know if we need its additional semantics or not.

**Comment by sdeleuze** [comment]
Closed without merging the proposed change as described in PR https://github.com/spring-projects/spring-reactive/pull/15, superseded by PR https://github.com/spring-projects/spring-reactive/pull/19.
