### ISSUE TITLE
Provide a way to configure the Content-Language HTTP header in response

### ISSUE THREAD

**Issue by danielfernandez** [spring-projects/spring-reactive#106]
Now that *content negotiation* is in place at the `View`/`ViewResolver` mechanism and therefore `View` implementations don't need to manually create the `Content-Type` HTTP header, it would be nice to have a similar mechanism that avoided the manual creation of the `Content-Language` header.

The current code at the *reactive* version of `ThymeleafView` (see [here](https://github.com/thymeleaf/thymeleafsandbox-springreactive/blob/31777ef358c36b2bd8ccd11234149cac5798dfee/src/main/java/thymeleafsandbox/springreactive/thymeleaf/ThymeleafView.java)) does something like:
```java
final HttpHeaders responseHeaders = exchange.getResponse().getHeaders();
if (templateLocale != null) {
    responseHeaders.set("Content-Language", templateLocale.toString());
}
```
However, in Spring MVC thanks to the `HttpServletResponse#setLocale(Locale)` method, all it had to do is:
```java
response.setLocale(templateLocale);
```
It's not that creating this header is extremely ugly code, but anyway IMHO it would be great if Spring Reactive included some kind of higher-level mechanism for setting this `Content-Language` that kept `View` implementations from having to create it manually.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14536
