### ISSUE TITLE
HTTP Status should not throw Exceptions

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#107]
Currently 4xx and 3xx status will throw an `HttpException`.

With REST I don’t think that a 4xx status is necessarily an exception that needs to be handled. Rather I just view this as a different type of result. Furthermore, using exceptions for a workflow (you often expect to get 4xx status in REST…ie if you are testing if a resource exists) can really degrade performance.

cc @smaldini @bclozel - Related to our Slack discussion

**Comment by smaldini** [comment]
Note that performance wise it costs as much as an allocation, we're not interested in the stack of that exception we create only from one place.

**Comment by rstoyanchev** [comment]
This should already work as expected. I believe currently `WebClient` doesn't raise an exception when extracting to a `ResponseEntity`. It raises an exception only if extracting the body.
