### ISSUE TITLE
Provide an equivalent to RequestContext

### ISSUE THREAD

**Issue by danielfernandez** [spring-projects/spring-reactive#108]
Spring MVC's `RequestContext` plays an important role with regard to form binding or other mechanisms such as themes or the use of the `RequestDataValueProcessor`.

But I see no current equivalents for these mechanisms in Spring Reactive yet, which means for now implementing a form-binding mechanism would not be possible…

**Comment by rstoyanchev** [comment]
Indeed, form binding is post M1 as per the high-level goals in https://jira.spring.io/browse/SPR-14161. Good to keep track of this though.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14533
