### ISSUE TITLE
Provide an abstraction for declaring filters or interceptors

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-reactive#111]
As a user I like the fact that I can write a Spring Bean and declare a `@RequestMapping` and it just works. It would be nice if there was a similar abstraction for filters (like `@WebFilter` from servlet spec) that worked for Spring beans independent of the platform. In Spring Boot we have quite a lot of features that work as filters, or configuring filters. The split between "business" implementation and path matching/configuration can be useful - it would be useful at least to be able to externalize the path matching part.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14530. @bclozel since you assigned yourself here I've also assigned you to SPR-14530 for now.
