### ISSUE TITLE
Rename getSupportedMimeTypes methods in Encoder and Decoder classes

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-reactive#113]
Since both `Encoder` and `Decoder` declare the `getSupportedMimeTypes` methods, one cannot implement both interfaces within the same class.

We should rename those to something like `getEncodingMimeTypes` and `getDecodingMimeTypes`.

**Comment by poutsma** [comment]
I would suggest `getEncodableMimeTypes()` and `getDecodableMimeTypes` instead.
