### ISSUE TITLE
JacksonJsonEncoder doesn't use type information in encode()

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-reactive#114]
Even though the method `encode` accepts a `ResolvableType elementType`, this information is not currently used in the implementation.

This could create issues with generic types.

**Comment by sdeleuze** [comment]
Closed by https://github.com/spring-projects/spring-reactive/commit/7d4d80358fa322916bb178dbf4e06dada52b31fd

**Comment by sdeleuze** [comment]
Closed by https://github.com/spring-projects/spring-reactive/commit/1fc82e17379e35c87d4b542c784369faae73ff54
