### ISSUE TITLE
Provide a URL-rewriting mechanism at ServerHttpResponse

### ISSUE THREAD

**Issue by danielfernandez** [spring-projects/spring-reactive#115]
SpringMVC-based applications make quite a lot of use of the URL-rewriting mechanism available at `HttpServletResponse#encodeUrl()`. This is normally done in a transparent way by the template engine.

This URL-rewriting mechanism allows the usage of several resource-management-oriented techniques, as well as of course setting URL-based session ids like `;jsessionid=x` in case browser cookies are disabled.

I cannot find anything similar to this in `ServerHttpResponse`, so I suppose this is something not implemented yet. And probably not to be until a later milestone, but I need it for Thymeleaf's new SpringReactive-specific *link builder* (in charge of building `@{...}` expressions), so I would like to keep track of when this gets implemented :)

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14529
