### ISSUE TITLE
Spring Data reactive templates and repositories

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#12]
As discussed with @christophstrobl, we should experiment on what Reactive support means for Spring Data.

Summary of the initial discussion:
- [CouchBase RxJava driver](http://blog.couchbase.com/why-couchbase-chose-rxjava-new-java-sdk) and/or [MongoDB Reactive Streams driver](http://mongodb.github.io/mongo-java-driver-reactivestreams/) support
- Internals based on Reactive Streams
- Spring Data Reactive templates may use `Publisher<T>` for streams or single async non-blocking element
- Repository level API will be provided for each composition library supported, for example a RxJava repository with `Single<T>` and `Observable<T>` based API, a Reactor repository with `Promise<T>` and `Stream<T>` based API, and maybe a generic one with `Publisher` (currently just Java 8 stream are supported)
- Spring Reactive codecs could be reused in Spring Data Reactive

**Comment by smaldini** [comment]
Arguments in favor of Publisher vs CompletableFuture:

- lazy execution and non opinionated threading (execute the query on request() thread), so rxjava/reactor can alter the Thread with subscribeOn()
- homogeneous API (plus and bad point :))

**Comment by sdeleuze** [comment]
Indeed, since these elements will be exposed as `Single`/`Stream` for the end users at repository level, and since these types are designed to be created from a `Publisher` of one element, it is perhaps better to keep only `Publisher` based template in order to avoid loosing semantics during the conversion. I am going to update the description.

**Comment by sdeleuze** [comment]
If we decide to use a `Publisher` for single result elements, it could be nice to identify them explicitly with a `@Single` annotation described in https://github.com/spring-projects/spring-reactive/issues/10

**Comment by sdeleuze** [comment]
Could be also nice to support this [Asynchronous PostgreSQL Java driver](https://github.com/alaisi/postgres-async-driver)!

**Comment by sdeleuze** [comment]
I have also found this [Reactive Couchbase experiment](https://github.com/jloisel/reactive-couchbase).

**Comment by sdeleuze** [comment]
I have made some progress:
 - [spring-reactive-playground](https://github.com/sdeleuze/spring-reactive-playground) shows a sample Spring Reactive application based on Mongo/Couchbase/Postgres Reactive drivers
 - This [Spring Data Commons reactive branch](https://github.com/sdeleuze/spring-data-commons/commit/reactive) shows a draft proposal of RxJava and Reactor Stream based repository interfaces (work in progress).

**Comment by sdeleuze** [comment]
The playground application will continue to evolve, but I think we can consider this issue as resolved.

**Comment by ccanning** [comment]
Just curios, why not consolidate and use the reactive streams API's instead of using each reactive implementations' dialect?

**Comment by sdeleuze** [comment]
Because with pure Reactive Streams [`Publisher`](http://www.reactive-streams.org/reactive-streams-1.0.0-javadoc/org/reactivestreams/Publisher.html) you can't do anything when used as a return value, it is too low level. More details about that in this ["A lite Rx API for the JVM" slides](https://speakerdeck.com/sdeleuze/a-lite-rx-api-for-the-jvm).

That's why on our API we use `Publisher` for input parameters (to be compatible with all RS based types like Reactor or the upcoming RxJava2), and Rx implementations for return types.

I plan to write a blog post on https://spring.io/blog/ in the coming weeks to explain that in detail.

**Comment by ccanning** [comment]
Thanks for the info.

Chuck
