### ISSUE TITLE
Support CharSequence encoding

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#120]
The `StringEncoder` can encode `String` but not `StringBuilder`, Groovy `GString`, etc. We can consider changing `StringEncoder` to be parameterized by `CharSequence` instead.

Note this was just added in 4.3 https://jira.spring.io/browse/SPR-13423 except we had no option to change the existing `StringHttpMessageConverter` and implemented directly in the return value handling.

**Comment by poutsma** [comment]
PR available at https://github.com/spring-projects/spring-framework/pull/1119
