### ISSUE TITLE
Support falling back on a default content type in CodecHttpMessageConverter

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#121]
The existing `AbstractHttpMessageConverter` has similar logic and it's useful in cases where a converter is picked based on the Object type (e.g. `SseEvent`, `Resource`) alone and/or where no concrete content type is picked resulting in "application/octet-stream" being passed in. 

See for example https://jira.spring.io/browse/SPR-12894 which is based on the `ResourceHttpMessageConverter` that supports content type `*/*`.

**Comment by sdeleuze** [comment]
Fixed by commit https://github.com/spring-projects/spring-reactive/commit/47265ede25b5b7bd12322be172f21cef57edfb42
