### ISSUE TITLE
Support `rx.Completable`

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#122]
The `ReactiveStreamsToRxJava1Converter` does not support `Completable`. It could with the Reactor `RxJava1CompletableConverter` except we need https://github.com/reactor/reactor-core/issues/106.

Beyond that `Completable` poses an additional challenge. Currently we check with the ConversionService if the return value or the target type (for argument resolvers) is convertible to/from a `Publisher` then we use the generic type as the element type for encoding/decoding. Here we have an async type that doesn't have generics. Can we assume `Void` as the element type?

**Comment by sdeleuze** [comment]
Implemented via https://github.com/spring-projects/spring-reactive/commit/745aea43830ed12641d0bbe8c3764946880e07aa.

**Comment by rstoyanchev** [comment]
Maybe we need  a separate ticket but I suspect Completable does not actually work with response body, response entity, and simple result handling.
