### ISSUE TITLE
Introduce writeAndFlushWith(Publisher<Publisher<DataBuffer>> body)

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#125]
As proposed by @rstoyanchev after some discussion raised by @poutsma, the best solution to deal with flushing is likely to add a `writeAndFlushWith(Publisher<Publisher<DataBuffer>> body)` to `ReactiveHttpOutputMessage` instead of using the current `FlushingDataBuffer` approach which is not perfect in term of OO design. That would be consistent with how Reactor deals with flushing, so let's try this approach.

**Comment by poutsma** [comment]
Fixed in 7b2196b408eeb55668a1add6455a4fd52adfdf38
