### ISSUE TITLE
Base for Reactive Http client

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#13]
It should be nice to experiment about a reactive HTTP client. It should be a useful addition to the server-side support, especially for Cloud and micro-services use cases.

**Comment by bclozel** [comment]
See #40

**Comment by sdeleuze** [comment]
Some thoughts discussed with @bclozel, thanks to the usage of the JSON decoder, I think the client is currently capable to handle `{"foo":"bar"}{"foo":"baz"}` (JSON streaming with no separator), `{"foo":"bar"}\r\n{"foo":"baz"}` (JSON streaming with carriage return separator) and `[{"foo":"bar"}n{"foo":"baz"}]` (JSON array) as real stream by creating a `Flux<T>` that will emit 2 elements.

In addition to that, it may be nice to support Server-Sent Events by maybe allowing to write something like `extract(sseStream(Person.class)` that will produce a `Flux<Person>` and complete when the connection is closed.
