### ISSUE TITLE
Check channel status before writing

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#131]
When testing Server-Sent Events with `spring-reactive-playground` sample app, I got a lot of exceptions in the logs because Spring Reactive try to write on a closed channel, see https://gist.github.com/sdeleuze/7c49d3353e507c94985b3af0a107885c. Maybe we could avoid that by adding additional checks on the channel status before writing each `DataBuffer` element.

Any thoughts @violetagg @poutsma @rstoyanchev ?

**Comment by poutsma** [comment]
This might be related to #59. Let's see if fixing that will fix this one as well.

**Comment by poutsma** [comment]
Can you give this another try, @sdeleuze ?

**Comment by sdeleuze** [comment]
Yes, I am going to update `spring-reactive-playground` to Spring Framework 5 and make a new try.

**Comment by sdeleuze** [comment]
@bclozel have updated [spring-reactive-playground](https://github.com/sdeleuze/spring-reactive-playground) to use the Reactive Boot stuff + `spring-web-reactive` module from Spring Framework 5.0, and I still have a lot of errors in the stacktrace when I close the browser while displaying the SSE page ([see updated logs](https://gist.github.com/sdeleuze/3953c2501bf08a0c0fd39340aa5b6eaf)).

@poutsma If you want to have a look, you just have to run `spring-reactive-playground`, open `http://localhost:8080` in your browser and close the browser.

**Comment by sdeleuze** [comment]
I will be on PTO next week so I assigned that to you @poutsma, even if this issue is not 100% blocking for M1 (this is just about error messages in logs).

@violetagg pointed out that maybe this issue in maybe just about filtering the error before logging it, as we do currently in websocket support, see https://github.com/violetagg/spring-framework/blob/master/spring-websocket/src/main/java/org/springframework/web/socket/sockjs/transport/session/AbstractSockJsSession.java#L374 for more details. We also need to keep in mind that the "Broken pipe" error message may vary depending on the network engine used.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14538
