### ISSUE TITLE
WebClient keep on excepting delayed response even in the presence of timeout

### ISSUE THREAD

**Issue by noorulhaq** [spring-projects/spring-reactive#138]
Hi,

I am trying to learn reactor project by developing a sample application. Below is the code snippet from the sample application.

<code>
public Mono<Quotation> findBestQuotation(Double loanAmount){

        return  Flux.range(1,9)
                .map(bankIndex -> "bank-"+bankIndex)
                .flatMap(bank -> requestForQuotation(bank, loanAmount)) // Scatter
                .collectList() // Gather
                .flatMap(quotations -> selectBestQuotation(quotations)).next();
    }
</code>

<br/>
<code>
    private Mono<Quotation> selectBestQuotation(List<Quotation> quotations){
        return Flux.fromIterable(quotations).sort((q1, q2) -> (q1.getOffer() > q2.getOffer()) ? 1:-1).next();
    }
</code>

<br/>
<br/>

<code>
public  Mono<Quotation> requestForQuotation(String bank, Double loanAmount) {

        ClientRequest<Void> request = ClientRequest.GET("http://localhost:8091/{bank}/quotation?loanAmount={amount}", bank, loanAmount)
                .accept(MediaType.APPLICATION_JSON)
                .build();

        Mono<Quotation> offer = WEB_CLIENT
                .exchange(request)
                .then(response -> response.bodyToMono(Quotation.class))
                .timeout(Duration.ofMillis(500)) // Response should come back within 500ms
                .otherwiseReturn(new Quotation("Pseudo-offer-from-"+bank,loanAmount)); // Fallback strategy

        return offer;
    }
</code>

    
**Scenario** 

What I am doing in above code snippet is I am requesting for loan quotations form multiple banks at "Scatter" phase then I am selecting the best quotation after "Gather" phase.

**Problem** 

I have deliberately added 4 sec delay in the bank service against one bank. The problem which I am facing here is that WebClient kept on accepting the delayed response from the bank service even though I have mentioned timeout of 500ms for expected response.  

This behavior is causing the problem in subsequent loan request because the response of former request is being received in the later loan request.

Any clue is much appreciated.

**Comment by sdeleuze** [comment]
Hey @noorulhaq, this project is not active anymore because the current development is done on https://github.com/spring-projects/spring-framework. I suggest you add `log()` operator to debug both client side and server side. I you have added a 4 sec delay, the server side should theorically wait before writing the response status code, but maybe there is a glitch.

If what you see with logs seems to be a bug, please raise an issue at https://jira.spring.io/browse/SPR.
