### ISSUE TITLE
Add @MessageMapping / @SubscribeMapping support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#17]
Likely to depend on https://github.com/spring-projects/spring-reactive/issues/16
Potentially includes a basic STOMP/SockJS support

**Comment by sdeleuze** [comment]
Closing that one in favor of https://github.com/spring-projects/spring-reactive/issues/16 in order to make it more easy to follow.

**Comment by sdeleuze** [comment]
Based on last week discussion, it is better to split the "low level websocket support" and "high level `@MessageMapping` and `@SubscribeMapping` support" discussions so I reopen this issue.

**Comment by sdeleuze** [comment]
Thinking about our programming model and how it could be used with Reactive types:
 - `@MessageMapping` is a message by message handler so no sure we need to support anything new here
 - It could make sens to support `@SubscribeMapping` methods that returns `Flux<T>` or `Observable<T>`. Each value emitted by the stream would produce a message sent to the client (default) or the broker (when `@SendTo` is used)
 - Implementations of methods like `MessageSendingOperations#convertAndSend(Object o)` could recognize `Flux<T>` and `Observable<T>` to send one message for each element emitted in the stream.

Any thoughts @bclozel and @rstoyanchev?

**Comment by sdeleuze** [comment]
As proposed yesterday by @rstoyanchev, `@MessageMapping` could be a stream processor, so we would have.

```java
@MessageMapping("/foo")
Flux<Bar> foo(Flux<Foo> fooFlux) {
	// ...
}
```

```java
@SubscribeMapping("/foo")
Flux<Bar> foo() {
	// ...
}
```

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14532
