### ISSUE TITLE
Request method based mapping

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#22]
This is not a high priority since Spring Reactive is a sandbox, but it could be nice to use the request method for the mapping (currently only the URL is used).

**Comment by smaldini** [comment]
I guess something in two flavors:
- `@Method(POST)` and @Post 
- functional API : post(Function) get(Function) etc

**Comment by sdeleuze** [comment]
The scope of what I propose here is just to be able to differentiate  `@RequestMapping(path= "/person", method = RequestMethod.GET)` from `@RequestMapping(path= "/person", method = RequestMethod.POST)` in order to make it easier for users (and for us) to experiment.

I would be in favor of waiting to see more progress on the client API side before any work on a potential server side functional API.
