### ISSUE TITLE
Build a sample app with Mongo/Couchebase/PostgreSql reactive drivers

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#23]
It could be nice to have some examples with Spring Reactive web support and [Mongo Reactive Streams](http://mongodb.github.io/mongo-java-driver-reactivestreams/)/ [Rxjava based Couchebase](http://docs.couchbase.com/developer/java-2.1/observables.html)  drivers.

This kind of end to end example could be a useful experiment for Spring Data Reactive support described in https://github.com/spring-projects/spring-reactive/issues/12, and for our upcoming work on dispatching customization, performance, etc.

**Comment by sdeleuze** [comment]
I also plan to experiment with this [Asynchronous PostgreSQL Java driver](https://github.com/alaisi/postgres-async-driver)

**Comment by sdeleuze** [comment]
I have implemented such application in [spring-reactive-playground](https://github.com/sdeleuze/spring-reactive-playground) project.

**Comment by making** [comment]
I've also created a sample application on Spring Boot.

https://github.com/making/demo-spring-reactive

**Comment by sdeleuze** [comment]
@making Nice, thanks for sharing :+1:
