### ISSUE TITLE
Refine Reactor use 

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#24]
We currently use reactor-stream for a few operations that could be considered core scope for Reactor:
- Building simple Publisher (just, from) 
 - Investigating switch to Publishers.just/from ...
- Combining Publishers (flatMap/merge/concat/concatMap)
 - Investigating switch to Processors.flatMap(function)...

There is also sometimes room for use of Publishers.create() and async facilities, which come with Reactor Core too, are optimized and are TCK ready.

Then to an extend, there are separate decisions wrt to : 
-  Buffer abstraction #7 part of reactor-core contract and goal to expose high order API on top of ByteBuffer.
- Reactor Net : currently depends on reactor-stream and reactor-bus, plus exposes routing features and unused ZeroMQ factories. Plan is to breakdown these modules in reactor-net, reactor-net-netty4, reactor-net-0mq and reactor-net-routing. Also under the new modules, dependencies could be reduced to reactor-core especially for reactor-net and reactor-net-netty (or -netty4).

**Comment by sdeleuze** [comment]
:+1: 

As a side note, being able to use a Java 8+ natively compliant Reactor (based on `java.util.function.*` would be awesome!

**Comment by sdeleuze** [comment]
Even if there is still some upcoming Reactor Net updates coming, I think with Reactor Core 2.5 M2 unified API now used we can close this issue.
