### ISSUE TITLE
Add static resource support

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#25]
I suppose it could be shaped like in spring mvc, and/or with annotation or functional API on request type (withFile). Caching should be a separate concern.

Possibly some impl like Netty will provide for transferTo ByteBuffer API.

**Comment by rstoyanchev** [comment]
In terms of high-level request handling everything is in place now for static resource handling --SimpleUrlHandlerMapping, SimpleHandlerAdapter, and SimpleResultHandler.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14521
