### ISSUE TITLE
Add redirect support on Response

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#26]
HTTP 302 redirects is common case and a Functional API on response like response.redirect() and response.redirectWith(Publisher<Void>) could be enough.

**Comment by danielfernandez** [comment]
Maybe this should be a ticket apart, but from the `ViewResolver` perspective it would also be needed to have an equivalent to Spring MVC's `RedirectView` so that the `ViewResolver` can return these when the view name specified at the controller starts with the `redirect:` prefix.

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14534
