### ISSUE TITLE
Add TCP support (or multi-protocol?)

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#28]
TcpHandler works in a few implementations but more generally speaking, what if we adapted to the same scope planned in reactive-ipc at first ?

IOHandler in general seems a good abstraction over all possible handlers covered by this model of consume, write+flush-on-complete and close. Plus we have codec facilities that applies to all sort of IO buffers. In general that would also unlock use of Spring Reactive into reactive distributed pipelines, e.g. the demanding dataflows found in banking or telco.

Possible implementation candidates : rxnetty (tcp), reactor-net (tcp, udp), reactor-aeron (uberfast udp)

**Comment by rstoyanchev** [comment]
We have this https://jira.spring.io/browse/SPR-14527 and we'll probably get to TCP support as part of STOMP/WebSocket support eventually.
