### ISSUE TITLE
Offer more Reactive facilities to Spring

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#29]
Spring Reactive has been focusing on web use cases but the scope doesn't possibly limit to this.
Helping Spring leveraging reactive programming in some construct would be significantly impacting.

For instance, a few of the reactor-spring ideas and other could be factored in spring-reactive:
- ApplicationEvent / ApplicationListener bridge and/or replacement
- BeanFactorySupplier : a lazy bean creation that injects a different supplier.get() on injection
- Something that converts a bean method into a Publisher

**Comment by rstoyanchev** [comment]
Closing this as an R&D item. We can re-open with specific requests as needed at Spring's JIRA.
