### ISSUE TITLE
Review request handling flow

### ISSUE THREAD

**Issue by smaldini** [spring-projects/spring-reactive#34]
There might be some room for improvements in the general request flow handling, the issues I observed are the following:
- Serialization and deserialization are mixed in argument resolution
- Writing response is in response handler
- Handling type extraction is done for each request
- Difficulty to see where to hook in "adds-on", e.g. global logging, security filter, global `dispatchOn` for handlers. We can also count in:
 - Type transformation that is not serialization : e.g. converting a `User` to `SecuredUser` or a `ByteBuffer` to `SseEvent` or `WebsocketMessage`
 - Global aggregations (required to re-construct some messages, e.g. Websocket Frames in Netty)
- A functional API might end up with such features exclusively, leaving pojo users with a less cool version of the API
- Workaround to handle pojo and Iterable input type users
- The questions raised in the issues #27 #28 or #33

Possible solutions include:
- High-level API for N "pre-processor", 1 "processor" (current handler) and N "post-processor" chain, 
 - Might be relevant to support similar arguments we support now in the various lifecycle stage, e.g. security is maybe more interested into the request rather than the payload, serialization might be different.
- Pre-resolution (bean post processing?) of requirements to add serialization, deserialization, pojo support, iterable support, publisher conversion and others in the chain
- A chain is materialized per request only -> subscribe
- Positioning in the chain could be hinted with processor identifiers ( e.g. `@Position(after="security")` ) like Netty handler
- Unsubscribed pipeline corresponding to a request should be cached, since building the pipeline is affected by various request mappings. As mentioned in a previous item, matching the request mapping method types instead of matching the url should be done once (so part of the pipeline might be pre-constructed). Unless we have a way to match url mappings without a request or give constant matchers (prefix `@Position(prefix="/users")`), the rest will have to be dynamically resolved from the request mapping registry.
- Functional API can naturally map to this approach by providing a Builder API to construct this chain.

**Comment by smaldini** [comment]
```java
  @PostProcessor(prefix="/users")
   public Publisher<ByteBuf> log(Publisher<ByteBuf> pub){
        return Streams.wrap(pub).log();
   }

   @RequestMapping("/users")
   public void saveUser(Observable<User> obs){
      obs.subscribe(this::doSomething);
   }
```

Would look like

```
       +----------+       +----------+       +----------+      +----------+    
       |          |       |          |       |          |      |          |    
       |  PrePro  |       | Convert  |       |  Handle  |      | PostPro  |    
+------>          +------->          +------->          +------>          +--->
       |          |       |          |       |          |      |          |    
       | Deserial.|       |  Pub2Obs |       | Dynamic! |      |          |    
       +----------+       +----------+       +----------+      +----------+    
````

**Comment by smaldini** [comment]
With #35, additional ideas came to fit in the scheme:
- Nothing prevents us to allow in this architecture multiple HttpHandler, if they do use a convention like `@Position(name="filters", after="ads")`. That would result in chaining the writeWith callbacks
- Pre and Post Processors can be the right place to also add compression, and pre/post static resources processing

**Comment by sdeleuze** [comment]
About the "concrete type of the boxes", one reason why I like "Spring type independent from any other contract" is that unlike with the operation types, we can be very flexible with the method arguments to provide dynamic inputs. Spring type approach allow to use singleton while for operation type you have to create a new instance for each request in order to pass most parameters to the constructor. Interop is fine since we use RS and `java.util.function` types.

**Comment by smaldini** [comment]
A simple design idea RequestFlowHandler : 
```java
interface HttpPreProcessor<I, II, O> extends Function<HttpFlow<I, O>, HttpFlow<II, O>>
interface HttpPostProcessor<I, O, OO > extends Function<HttpFlow<I, O>, HttpFlow<I, OO>>
interface HttpProcessor<I, II, O, OO> extends HttpPreProcessor<I, II, O>, HttpPostProcessor<I, O, OO>

class HttpFlow<IN, OUT> {
  final HttpServerRequest request;
  final HttpServerResponse response;

  //Constructor

  public Publisher<IN> in(){ return request.getBody(); }
  public Publisher<OUT> out(){ return Publishers.empty(); }
}

public Publisher<Void> handle(ServerHttpRequest request, ServerHttpResponse response){
  Publisher<HttpFlow<ByteBuffer, ByteBuffer> root = Publishers.just(new HttpFlow(request, response));
  return s -> {
         Publisher last = root;
         Iterable<PreProcessor<?, ?, ByteBuffer>> preprocs = 
             resolvePreProcessors(request, response);

         for(PreProcessor<ByteBuffer, ?, ByteBuffer> preproc : preprocs){
               last = Publishers.map(last, preproc);
         }
        Iterable<HttpProcessor<?, ?, ?, ?>> procs = 
             resolveProcessors(request, response);

         for(HttpProcessor<?, ?, ?, ?> proc : procs){
               last = Publishers.map(last, proc);
         }
        
         Iterable<PostProcessor<?, ?, ?> postprocs = 
             resolvePostProcessors(request, response);

         for(PostProcessor<?, ?, ?> postproc : postprocs){
               last = Publishers.map(last, postproc);
         }
         response.writeWith((Publisher<ByteBuffer>)last).subscribe(s);
  }
}

```

**Comment by rstoyanchev** [comment]
For the RequestFlowHandler I can appreciate the construction of a chain that is only materialized on subscribe. That is something to think about.

However the Pre/Post/Processor is just a generic processing chain that doesn't help me envision where framework specific functionality fits vs application specific functionality. Each Processor is a function that maps from request-response from one generic type to another. I can see how I can do serialization, deserialization, and other ways of transforming the request and response. What I don't see is how to map the request and response to a handler, mapping the selected handler to a handler result, then the handler result to a completion publisher.

**Comment by smaldini** [comment]
Mostly solved by https://github.com/spring-projects/spring-reactive/commit/605375dede2f622dd2844e19c29b9e357911fa7c

There are still fines to refine but we can open separate issues.
