### ISSUE TITLE
Progressive HTML rendering support.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-reactive#35]
Improving the perceived performance of a web page by displaying content to the user as fast as possible is a well-known trade in web frontend development.
I wonder whether this could be supported in Spring Reactive Web :)

http://www.ebaytechblog.com/2014/12/08/async-fragments-rediscovering-progressive-html-rendering-with-marko/

**Comment by sdeleuze** [comment]
:+1:

**Comment by smaldini** [comment]
That's spot on Thomas ! To connect with #25.

**Comment by rstoyanchev** [comment]
Closing this as an R&D item for now. We can re-open as a ticket in Spring's JIRA once the idea materializes a little more.
