### ISSUE TITLE
Randomly reproducible unit test error

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#37]
Sometimes this error occur, maybe something to fix at `RequestMappingHandlerMapping#methodMap` level.

```java
java.lang.AssertionError: expected:<public java.lang.String org.springframework.reactive.web.dispatch.method.annotation.RequestMappingHandlerMappingTests$TestController.getFoo()> but was:<public java.lang.String org.springframework.reactive.web.dispatch.method.annotation.RequestMappingHandlerMappingTests$TestController.foo()>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.springframework.reactive.web.dispatch.method.annotation.RequestMappingHandlerMappingTests.method(RequestMappingHandlerMappingTests.java:69)
```

**Comment by sdeleuze** [comment]
I am closing this issue for now since I am not able to reproduce it anymore. I suspect some recent changes have fixed it as a side effect. Fell free to reopen if you see it again.

**Comment by rstoyanchev** [comment]
The error is still there and it's due to the naive implementation of RequestMappingHandlerMapping which returns the first match it finds. It doesn't have any logic to pick the best match. Perhaps we should address this for now by changing the test. Basically we don't support yet what the test does.
