### ISSUE TITLE
Should we introduce a type to be used instead Publisher<Void>?

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#49]
In various places in our codebase, we are returning `Publisher<Void>` to express that the something will be complete later, without any value emitted.

As reported by @rstoyanchev we should introduce a dedicated type instead of `Publisher<Void>`, mainly because `Publisher` purpose is to be a stream of elements, and in that case there is no element, just a complete signal.

You can see related interesting RxJava discussions:
 - [`Observable<Void>` Usage or `VoidObservable`](https://github.com/ReactiveX/RxJava/issues/3037)
 - [`RxJava Completable extension`](https://github.com/akarnokd/RxJavaCompletable)

I would be in favor of creating an interface with default methods for this type.

About the name, I am not sure but perhaps `Listenable` could be a good fit, since we have already `ListenableFuture` in Spring, or `Deferred` since we also have `DeferredResult`, or `Completable` since it is about something that will complete at some point.

Maybe it could provide operators that make sense for such value less completable object, like `concat`.

I am also wondering it it should extends `Publisher<Void>`, or as an alternative provide a `Publisher<Void>` default method for interoperability?

Any thoughts?

**Comment by sdeleuze** [comment]
I think `Deferred` is my preferred one.

**Comment by sdeleuze** [comment]
I think `Deferred` is my preferred one, or maybe something like `DeferredSignal` ...

**Comment by poutsma** [comment]
I'm not saying it's the best name, but should at least consider `VoidPublisher`, following RxJava's approach.

I'm not sure about `DeferredSignal`. Doesn't the term signal already have a specific meaning with Reactive Streams? I thought that onNext, onError, onComplete are all signals.

**Comment by smaldini** [comment]
We weren't satisfied 3 years ago with Deferred for Stream purpose in reactor and in our case it became Broadcaster/Processor, so the meaning might be confusing,

**Comment by sdeleuze** [comment]
Indeed, `VoidPublisher` is also a name to consider, especially if it extends `Publisher<Void>`.

**Comment by sdeleuze** [comment]
As expressed in https://github.com/spring-projects/spring-reactive/issues/50, I think our custom publishers should:
 - Have a name like `FooPublisher`
 - Be interfaces with default methods
 - Extends `Publisher`

So maybe `VoidPublisher` or `CompletablePublisher`...

**Comment by sdeleuze** [comment]
Or maybe using `PromisePublisher<Void>` is just fine after all ...

**Comment by sdeleuze** [comment]
RxJava `Completable` type has been merged in their master branch, so it will be available in next 1.x release. So that may be a +1 for getting a dedicated type in Spring Reactive as well.

**Comment by sdeleuze** [comment]
Another solution proposed by @smaldini is to just use `Promise<Void>` (as defined in issue https://github.com/spring-projects/spring-reactive/issues/50).

**Comment by sdeleuze** [comment]
Fixed by https://github.com/spring-projects/spring-reactive/commit/a945d1cfca467b10a52106594e9b99779e34887f, let's see how it goes with the [`Mono<Void>`](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/Mono.java), the lite Rx type for single element stream from Reactor Core 2.5
