### ISSUE TITLE
Make it possible to run blocking handler methods in a dedicated thread

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#56]
In a Reactive webapp, even if it is best practice to perform IO intensive operations (network, database) with non-blocking libraries (see issue #23), blocking libraries are widely available and we should support them. JDBC (blocking) API is a good example of such need.

We should explore how Spring Reactive should support that, maybe by providing a way to run the blocking handler methods in a dedicated thread.

How we trigger this "blocking handler method dispatched on another thread" mechanism has to be determined:
 - When non Reactive types are returned
 - Dedicated annotation (Spring Framework already provide `@Async`, but is it a good fit here?)
 - ...

**Comment by snicoll** [comment]
I like that and this would probably require a significant amount of work in the core container. SQL operations typically require a transaction so we should make sure to transmit the transaction handle accordingly. Happy to help if you want to brainstorm this.

**Comment by joaoevangelista** [comment]
This reminded me of Vert.x `blockingHandler`, they use this to not block the Netty's NioEventLoop when a task will block more than an amount of time. From my Spring's user POV, some dedicated annotation would be helpful to distinguish between the normal `@Async`, maybe something like  a `@Blocking` annotation, so drivers wrappers, spring-data integration modules and user specific methods could use this. Spring `TaskExecutor` API could help too, and spring-reactive could provide a configuration to this executor, providing for example a [Reactor WorkQueue Impl](https://github.com/reactor/reactor-spring/blob/master/reactor-spring-core/src/main/java/reactor/spring/core/task/WorkQueueAsyncTaskExecutor.java ) or something like. Then the user just need to enable everthing by the `@EnableReactive` kind of annotation

**Comment by rstoyanchev** [comment]
Closing this ticket as it is more of an R&D idea. My sense is that this is something that naturally fits in the API of the reactive library being used but we can always open a new ticket in Spring's JIRA as needed.
