### ISSUE TITLE
Fix SocketException in Reactor Net integration tests

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#57]
Tests where there is no response body writing and no explicit calls to send headers result in a SocketException on the client side. See the [latest build failures](https://build.spring.io/browse/SR-PUB-106/) for example. 

The expectation is that Reactor Net should work fine if the handler for the request completes without explicitly causing headers to be written (or writing the response body).

Also see [related commit](https://github.com/spring-projects/spring-reactive/commit/9c7151f44da976b1218ed4eee1355bbd0705a775).

**Comment by sdeleuze** [comment]
This issue has been fixed on Reactor side, and the Reactor tests has been uncommented by https://github.com/spring-projects/spring-reactive/commit/881a70b6ca1919f117f75ba7b0ce3fd1c8887ea2.
