### ISSUE TITLE
WebSessionIdResolver.resolveSessionId should return an ordered collection of String

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#64]
The reason is that the same session can be present in the request multiple times. For example, you might have a session cookie named SESSION for example.com and application.example.com

In that instance you wouldn’t know which id was valid for this specific application until you looked it up using `WebSessionManager`

Related https://tools.ietf.org/html/rfc6265#section-5.4

**Comment by rstoyanchev** [comment]
I've modified [WebSessionIdResolver](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/web/server/session/WebSessionIdResolver.java) to return a List. However the code that's using it is only picking up the first session id. How should it actually work?

**Comment by rwinch** [comment]
@rstoyanchev Any time you try to resolve the `WebSession` in `WebSessionManager` you should try each session id until a `WebSession` is resolved.
