### ISSUE TITLE
Provide WebSession <T> T getAttribute(String)

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#65]
I discussed this with @rstoyanchev  and it may be nice to provide support for automatic casting of the `WebSession` attributes. For example we might provide the following method on `WebSession`:

```java
<T> T getAttribute(String)
```

A similar method might be beneficial for `ServerWebExchange`. For example adding the following method to `ServerWebExchange`:

```java
<T> T getAttribute(String)
```

**Comment by rstoyanchev** [comment]
This is now in.
