### ISSUE TITLE
Failed to switch WebSessionIntegrationTests to use the new WebClient 

### ISSUE THREAD

**Issue by rstoyanchev** [spring-projects/spring-reactive#70]
Now that we have `WebClient` I tried updating `WebSessionIntegrationTests` as part of looking into adding client-side cookie support but ran into issues (see https://github.com/rstoyanchev/spring-reactive/tree/web-session-int-tests). 

I fixed one such issue with https://github.com/spring-projects/spring-reactive/commit/81ae92878b36414ca32ce2da5ffe0af0747c03a7. However the tests still do not pass. What I'm observing is that for each request the server may be invoked multiple times.

**Comment by bclozel** [comment]
I've looked into this and found that indeed, duplicate requests are sent from the client - I've confirmed that with Wireshark as well.
The logs seem to show there's an issue with the request/response publisher lifecycle:

```
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-1> - [1]. onSubscribe(reactor.core.publisher.FluxMap$MapSubscriber@21b627e1)
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-2> - [2]. onSubscribe(reactor.core.publisher.FluxMap$MapSubscriber@5a234d3)
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-1> - [1]. request(unbounded)
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-2> - [2]. cancel()
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-2> - [2]. request(unbounded)
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-1> - [1]. onNext(ReactorClientHttpResponse{request=GET /,status=200})
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-1> - [1]. onComplete()
INFO [org.springframework.http.client.reactive] <reactor-tcp-io-1> - [1]. cancel()
```
Two subscriptions, one being cancelled right away!.

Workaround: switching to the RxNetty client implementation:
```
this.webClient = new WebClient(new RxNettyHttpClientRequestFactory(new NettyDataBufferAllocator(ByteBufAllocator.DEFAULT)));
```

**Comment by bclozel** [comment]
This can now be applied - but first the build should be upgraded to the latest reactor-core `2.5.0-BUILD-SNAPSHOT`.
