### ISSUE TITLE
Make sure the build last shorter 

### ISSUE THREAD

**Issue by poutsma** [spring-projects/spring-reactive#73]
Currently, the `/stream-result` path of `RequestMappingIntegrationTests` takes 5 seconds per server to run, which as of writing this comes do 25 seconds. This is a bit long.

Unfortunately, when reducing the time to .5 seconds per server, the build hangs for unclear reasons. This should be fixed.

See https://github.com/spring-projects/spring-reactive/blob/master/src/test/java/org/springframework/web/reactive/method/annotation/RequestMappingIntegrationTests.java#L468

**Comment by sdeleuze** [comment]
Fixed by https://github.com/spring-projects/spring-reactive/commit/2d0fa0cc6786b1ce16ba245ef5d113157aea0530, it seems Reactor Core + Spring Reactive now handle correctly shorter interval for the stream result test.

**Comment by sdeleuze** [comment]
Reopening since the test was ignored.

**Comment by sdeleuze** [comment]
Fixed by 4518341d377f02dbd893139be504592ad63454ae and 7489232f6a69af7bd2c63b2015317617d012e325 and
