### ISSUE TITLE
Support defaults for WebClient requests

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#79]
It would be nice if we could provide defaults for requests to a client.

For example, make `WebClient` default to use `application/json` accept header, have a base URL of `https://example.com/foo/`, include basic authentication header of rob:secret, etc?

**Comment by bclozel** [comment]
See the equivalent feature in Spring MVC: [MockMvc.setDefaultRequest](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/web/servlet/MockMvc.java#L94-L100) and an [example usage](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/test/java/org/springframework/test/web/servlet/samples/standalone/resultmatchers/XmlContentAssertionTests.java#L66-L70).

**Comment by bclozel** [comment]
@rwinch Should I still consider this feature or did #88 provide what's needed?

If not, what's the difference between those two features?

**Comment by rwinch** [comment]
@bclozel Thanks for pointing this duplicate out. This is now resolved via #88 as you mentioned. Closing...
