### ISSUE TITLE
Generics support for WebResponseExtractors

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#89]
WebResponseExtractors should easily support extracting generics (i.e. `Map<String,String>`). Perhaps through use of ~~`ParameterizedTypeReference`~~ `ResolvableType`.

**Comment by sdeleuze** [comment]
+1 for exposing this in the public API, but I would prefer using `ResolvableType` instead of `ParameterizedTypeReference`.

**Comment by rwinch** [comment]
@sdeleuze Good suggestion! I updated the issue.
