### ISSUE TITLE
Consider Providing concept similar to servlet forwarding

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#93]
Here is a scenario I find it very useful:

Someone is using Spring Security and we need to present the user with an “authentication prompt”. Often times this will vary by content type. So for example, I might need to return an HTTP Basic prompt for application/json but redirect to an HTML page for html request. In the json case the result might even contain some JSON in the body giving the error message.

If we support a concept like forward, this can make it easy to define a Spring `@RequestMapping` endpoint to process it. This means that the user can easily leverage things like type conversion, argument resolvers, etc.

Otherwise, (as far as I can tell) Spring Security must provide support for all these things or handicap the user with a less flexible API.

I do acknowledge having different “dispatch” types adds quite a bit of complexity, so that might not be worth the tradeoff. However, I thought it was worth bringing up for discussion

@rstoyanchev points out that this would be useful in error handling (i.e. similar to global error handler "forwards" to a controller)

**Comment by sdeleuze** [comment]
Is it a duplicate of https://github.com/spring-projects/spring-reactive/issues/27 ?

**Comment by rstoyanchev** [comment]
Yes I think they're. Let's use this one.

**Comment by rwinch** [comment]
@sdeleuze Thanks for pointing that out!

**Comment by rstoyanchev** [comment]
Superceded by https://jira.spring.io/browse/SPR-14537
