### ISSUE TITLE
Create way for "retrying" request

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-reactive#94]
It would be nice to support a way or hook to retry a request within the reactive client. This would be useful in at least a few circumstances that I can think of:

## Rate Limiting

There are many APIs that perform rate limiting and may provide a response that indicates the client should not try again until a specific time. It would be nice if the client had a first class way (or hook) to handle a response and retry a request.

[GitHub APIs](https://developer.github.com/v3/rate_limit/) provides an example of this 

## OAuth Access Token Timeouts

OAuth provides short lived tokens that eventually expire. An API endpoint might indicate that the access token is now expired and the client needs to refresh the credentials.

It would be nice if the client API would provide a first class mechanism (or hook) to allow handling a response that allows making an additional request (i.e. refreshing the access token), and then performing  the original request (modified only with the new token)

**Comment by smaldini** [comment]
Actually reactor-netty supports multi subscribe so doing
```java
httpClient.get("http://xxxx").retry(3).subscribe();
```

**Comment by bclozel** [comment]
I think the OAuth use case should be covered by #91.
As for the `retry` operator support in WebClient, I'll add more tests to verify it works properly.

**Comment by rwinch** [comment]
@bclozel Thanks for the reply. To be clear for the OAuth use case I'd like to:

* Make a request
* The request fails
* Automatically make another request (to obtain an access token)
* Update the original request and retry it

This is achievable with #91?

**Comment by bclozel** [comment]
I think this can be done with #91, but the `RestTemplate` interceptor feature is not currently used in spring-security's `OAuth2RestTemplate`. I don't know if there's a known limitation that prevented it or if it's just a design choice. I'll dig into this.

**Comment by rstoyanchev** [comment]
Resolving for now but @bclozel feel free to create a new ticket in SPR if there is anything that needs to be added.
