### ISSUE TITLE
Native HATEOAS client-side support

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-reactive#95]
As demonstrated [in Spring HATEOAS `Traverson` class](http://docs.spring.io/spring-hateoas/docs/current/reference/html/#client), that would be nice to support natively following HATEOAS links in Reactive HTTP client.

It is interesting to notice that async support for such need has been requested in this great [Implementing HAL hypermedia REST API using Spring HATEOAS](https://opencredo.com/hal-hypermedia-api-spring-hateoas/).

If we think this is not enough a core concern, at least an extension point that could allow such feature would be nice.

cc @olivergierke @wilkinsona @gregturn

**Comment by rstoyanchev** [comment]
Closing this is a discussion idea. We can re-open in Spring's JIRA if we resolve to do this.
